Updated the Tensorboards Operator Readme
canonical/kubeflow-tensorboards-operator pull request #29
Opened 2022-09-07 08:56 UTC by NohaIhab

2022-09-07 09:26 UTC, DomFleischmann requested changes
Looks good, just some small changes required.

2022-09-07 09:26 UTC, DomFleischmann commented on README.md
> +juju deploy tensorboards-web-app --trust
is `--trust` required for these charms?

2022-09-07 09:26 UTC, DomFleischmann commented on README.md
> +juju deploy tensorboards-web-app --trust
I also believe we should point to `--channel=latest/edge` here, this is the README for main so with latest/edge we actually deploy what currently on main.

2022-09-07 09:26 UTC, DomFleischmann commented on README.md
> +juju relate istio-pilot:ingress tensorboards-web-app:ingress
We are also missing the gateway relation between tensorboard-controller and istio-pilot which is added in `latest/edge`

2022-09-07 09:26 UTC, DomFleischmann commented on README.md
> +### What’s included in Charmed Kubeflow 1.4
lets remove the 1.4 part here.

2022-09-07 11:21 UTC, natalian98 commented on README.md
> +juju deploy tesnorboard-controller --channel=latest/edge
just a small typo
```suggestion
juju deploy tensorboard-controller --channel=latest/edge
```

2022-09-07 11:51 UTC, natalian98 commented on README.md
> +Charmed Kubeflow is free software, distributed under the [Apache Software License, version 2.0](https://github.com/canonical/dex-auth-operator/blob/master/LICENSE).
How about pointing to bundle-kubeflow's [license](https://github.com/canonical/bundle-kubeflow/blob/main/LICENSE)?

2022-09-07 11:56 UTC, natalian98 commented on README.md
> +[https://github.com/canonical/dex-auth-operator/issues](https://github.com/canonical/dex-auth-operator/issues)
Let's point to tensorboards repo instead
```suggestion
https://github.com/canonical/kubeflow-tensorboards-operator/issues
```

2022-09-08 11:27 UTC, DomFleischmann approved these changes

2022-09-08 11:27 UTC, merged